name: CI

on:
  push: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: uv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
      
      - name: Install uv
        run: pip install --upgrade uv
      
      - name: Install project + dev deps
        run: |
          uv venv .venv
          . .venv/bin/activate
          uv pip install -e . --group dev
      
      - name: Run pytest
        run: |
          . .venv/bin/activate
          uv run pytest -q --disable-warnings
