name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache uv (Linux only)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}

      - name: Create venv & install deps
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade uv
          uv pip install -e . --group dev

      - name: Run pytest
        shell: bash
        run: |
          source .venv/bin/activate
          uv run pytest -q --disable-warnings
