name: Publish to PyPI

on:
  release:
    types: [released]

jobs:
  build-and-publish:
    environment: pypi 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Install deps
        run: |
          pip install --upgrade uv
          uv pip install --upgrade build twine
      
      - name: Build package
        run: uv run python -m build --sdist --wheel --outdir dist
      
      - name: Twine check
        run: |
          twine check dist/*
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verify-metadata: true
